// functions/api/*.js 를 원천으로 Pages advanced mode 워커(dist/_worker.js)의 소스를 만든다.
//
// 왜: 릴리스 파이프라인은 봉인된 dist 만 배포한다(gitops landing-last). functions/ 는 dist 밖이라
// 2026-09-21 운영에서 /api/* 가 통째로 404 가 됐다. 함수를 dist 안에 두면 "올라가는 바이트 전부가
// dist_sha256 에 묶인다"가 다시 참이 되고, dist 만 올려도 함수가 같이 간다.
//
// 번들러를 쓰지 않는다. 출력은 입력 바이트의 순수 함수여야 한다 — Windows 에서 계산한 dist 해시를
// Linux CI 가 그대로 재현해야 하기 때문이다(경로·OS 가 섞이면 봉인이 깨진다).
import { readdirSync, readFileSync, statSync } from 'node:fs';

const FILE_NAME = /^[a-z0-9][a-z0-9-]*\.js$/;
const HANDLER = /^export (async function|function) (onRequest(?:Get|Post|Put|Patch|Delete|Head|Options)?)\b/gm;

function fail(path, reason) {
  throw new Error(`functions/${path}: ${reason}`);
}

function readHandlers(path, raw) {
  const source = raw.replace(/\r\n/g, '\n');
  if (source.includes('\r')) fail(path, '줄바꿈이 LF/CRLF 가 아니다');
  // 스코프로 감싸 한 파일에 합치므로 모듈 경계를 넘는 것은 옮길 수 없다.
  if (/^\s*import\s/m.test(source) || /\bimport\s*\(/.test(source) || /\brequire\s*\(/.test(source)) {
    fail(path, 'import/require 는 _worker.js 로 묶을 수 없다 — 함수는 자기완결이어야 한다');
  }
  const handlers = [...source.matchAll(HANDLER)].map((match) => match[2]);
  if (handlers.length === 0) fail(path, 'onRequest* 핸들러가 없다');
  if (new Set(handlers).size !== handlers.length) fail(path, '같은 핸들러가 두 번 선언됐다');
  const exportLines = source.split('\n').filter((line) => /^\s*export\b/.test(line)).length;
  if (exportLines !== handlers.length) fail(path, 'onRequest* 핸들러 밖의 export 는 허용하지 않는다');
  const body = source.replace(HANDLER, '$1 $2');
  return { handlers, body: body.endsWith('\n') ? body : `${body}\n` };
}

function collect(functionsDir) {
  const tops = readdirSync(functionsDir).sort();
  if (tops.length !== 1 || tops[0] !== 'api') fail('', `최상위는 api 하나여야 한다(_routes.json 의 /api/* 와 짝): ${tops.join(', ')}`);
  const routes = [];
  for (const name of readdirSync(`${functionsDir}/api`).sort()) {
    const path = `api/${name}`;
    if (statSync(`${functionsDir}/${path}`).isDirectory()) fail(path, 'api 아래의 중첩 디렉터리는 지원하지 않는다');
    if (!name.endsWith('.js')) continue;
    if (!FILE_NAME.test(name)) fail(path, '파일 이름은 소문자·숫자·하이픈이어야 한다(동적 세그먼트·미들웨어 불가)');
    routes.push({ route: `/api/${name.slice(0, -3)}`, path, ...readHandlers(path, readFileSync(`${functionsDir}/${path}`, 'utf8')) });
  }
  if (routes.length === 0) fail('api', '묶을 함수가 없다');
  return routes;
}

export function renderPagesWorker(functionsDir) {
  const routes = collect(functionsDir);
  const lines = [
    '// GENERATED by build.mjs (scripts/pages-worker.mjs) from functions/api/*.js - do not edit.',
    '// Cloudflare Pages advanced mode: the sealed dist carries its own Functions, so a release that',
    '// deploys dist alone keeps /api/* alive. _routes.json limits invocations to /api/*.',
    'const ROUTES = new Map();',
    '',
  ];
  for (const { route, path, handlers, body } of routes) {
    lines.push(`// ---- functions/${path}`);
    lines.push(`ROUTES.set('${route}', (() => {`);
    lines.push(body.replace(/\n$/, ''));
    lines.push(`return { ${handlers.join(', ')} };`);
    lines.push('})());');
    lines.push('');
  }
  lines.push(
    'const METHODS = { GET: "Get", POST: "Post", PUT: "Put", PATCH: "Patch", DELETE: "Delete", HEAD: "Head", OPTIONS: "Options" };',
    '',
    'export default {',
    '  async fetch(request, env, ctx) {',
    '    const handlers = ROUTES.get(new URL(request.url).pathname);',
    '    const method = METHODS[request.method];',
    '    const handler = handlers && ((method && handlers[`onRequest${method}`]) || handlers.onRequest);',
    '    // Anything that is not an exact function route + method is a static asset request.',
    '    if (!handler) return env.ASSETS.fetch(request);',
    '    return handler({',
    '      request,',
    '      env,',
    '      params: {},',
    '      data: {},',
    '      next: () => env.ASSETS.fetch(request),',
    '      waitUntil: (promise) => ctx?.waitUntil?.(promise),',
    '      passThroughOnException: () => ctx?.passThroughOnException?.(),',
    '    });',
    '  },',
    '};',
    '',
  );
  return lines.join('\n');
}
